import Header from "@/components/Header/Header";
import "../styles/globals.scss";

export const metadata = {
  title: "Advanced Tic Tic Toe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
